GET http://localhost:9000/api/userhistory/1 HTTP/1.1

####

POST http://localhost:9000/api/createitem/1
Content-Type: application/json

{
    "id": 9,
    "project": "test9",
    "startTime": 0,
    "endTime": 1,
    "note": "note9"
}

####

POST http://localhost:9000/api/login
Content-Type: application/json

{
    "userName": "potato",
    "password": "uhm"
}